### ISSUE TITLE
DF 10, addon ver 34.1, errors

### ISSUE THREAD

**Issue by sidain** [kemayo/wow-appearancetooltip#10]
Not sure where to put this, but I am getting these errors with df client 10 and addon ver 34.1

 

1x .../LibAppropriateItems-1.0-1/LibAppropriateItems-1.0.lua:41: table index is nil
[string "@Interface/AddOns/AppearanceTooltip/lib/LibAppropriateItems-1.0-1/LibAppropriateItems-1.0.lua"]:41: in main chunk

Locals:
lib = <table> {
 CanEquip = <function> defined @Interface/AddOns/AppearanceTooltip/lib/LibAppropriateItems-1.0/LibAppropriateItems-1.0.lua:8
 IsAppropriate = <function> defined @Interface/AddOns/AppearanceTooltip/lib/LibAppropriateItems-1.0/LibAppropriateItems-1.0.lua:14
}
oldMinor = nil
_ = "Paladin"
playerclass = "PALADIN"
valid_classes = nil
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "table index is nil"

1x Interface/AddOns/AppearanceTooltip/cameraids.lua:62: table index is nil
[string "@Interface/AddOns/AppearanceTooltip/cameraids.lua"]:62: in main chunk

Locals:
myname = "AppearanceTooltip"
ns = <table> {
 SLOT_WAIST = 6
 SLOT_TABARD = 19
 SLOT_OFFHAND = 17
 always_remove = <table> {
 }
 SLOT_MAINHAND = 16
 Debug = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:694
 CanTransmogItem = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:603
 Print = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:691
 ColorTextByCompletion = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:686
 SLOT_FEET = 8
 slot_removals = <table> {
 }
 UpdateSources = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:571
 PlayerHasAppearance = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:617
 ShowItem = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:310
 SLOT_HANDS = 10
 SLOT_SHOULDER = 3
 SLOT_ROBE = -99
 ResetModel = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:457
 modifiers = <table> {
 }
 slot_facings = <table> {
 }
 HideItem = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:453
 SLOT_CHEST = 5
 ComputeTooltipAnchors = <function> defined @Interface/AddOns/AppearanceTooltip/addon.lua:199
 SLOT_SHIRT = 4
}
races = <table> {
 1 = "Human"
 2 = "Orc"
 4 = "NightElf"
 8 = "Troll"
 32 = "KulTiran"
 9 = "Goblin"
 35 = "Vulpera"
 36 = "MagharOrc"
 5 = "Scourge"
 10 = "BloodElf"
 11 = "Draenei"
 22 = "Worgen"
 3 = "Dwarf"
 6 = "Tauren"
 24 = "Pandaren"
 25 = "Pandaren"
 37 = "Mechagnome"
 26 = "Pandaren"
 34 = "Dwarf"
 7 = "Gnome"
 31 = "ZandalariTroll"
 28 = "HighmountainTauren"
 30 = "LightforgedDraenei"
 29 = "VoidElf"
 27 = "Nightborne"
}
genders = <table> {
 0 = "Male"
 1 = "Female"
}
slots = <table> {
 INVTYPE_BODY = "Shirt"
 INVTYPE_HEAD = "Head"
 INVTYPE_FEET = "Feet"
 INVTYPE_WRIST = "Wrist"
 INVTYPE_TABARD = "Tabard"
 INVTYPE_SHOULDER = "Shoulder"
 INVTYPE_HAND = "Hands"
 INVTYPE_WAIST = "Waist"
 INVTYPE_ROBE = "Robe"
 INVTYPE_LEGS = "Legs"
 INVTYPE_CLOAK = "Back"
 INVTYPE_CHEST = "Shirt"
}
item_slots = <table> {
 INVTYPE_2HWEAPON = true
 INVTYPE_SHIELD = "Shield"
 INVTYPE_RANGEDRIGHT = true
 INVTYPE_HOLDABLE = "Offhand"
 INVTYPE_WEAPONOFFHAND = true
 INVTYPE_WEAPONMAINHAND = true
 INVTYPE_RANGED = true
 INVTYPE_WEAPON = true
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"

1x Interface/AddOns/AppearanceTooltip/lib/LibAppropriateItems-1.0-1/LibAppropriateItems-1.0.lua:1 (null)

1x Interface/AddOns/AppearanceTooltip/cameraids.lua:1 (null)

1x FrameXML\Bindings.xml:1 Interface/AddOns/AppearanceTooltip/lib/LibAppropriateItems-1.0/LibAppropriateItems-1.0.lua:1 (null)

1x FrameXML\Bindings.xml:1 Interface/AddOns/AppearanceTooltip/cameraids.lua:1 (null)

**Comment by kemayo** [comment]
Is this on the PTR/beta? (It's because LE_ITEM_WEAPON_GENERIC isn't set -- which it should still be, because although it was deprecated in 9.1.0 it still hasn't been *removed*.)

**Comment by sidain** [comment]
Could it be something with my saved variables, they are very old, I have been using Appearance Tooltip since its inception?

**Comment by kemayo** [comment]
That shouldn't be able to cause anything like this. That said, this should be fixed in the current alpha build: I updated AppearanceTooltip (1058adfee8624277bbd85ef3b7cf052b17c9a7e3) and LibAppropriateItems-1.0 (https://github.com/kemayo/wow-lib-appropriateitems/commit/98d04618863959ed4b262fee4e884f0addf5feae) to not use those deprecated constants any more.

**Comment by sidain** [comment]
ty
