### ISSUE TITLE
Window only shows undressed player and never shows appearances 

### ISSUE THREAD

**Issue by Beet4** [kemayo/wow-appearancetooltip#12]
I don't know if this happened on 10.0.2 or 10.0.0 or with the latest update of AppearanceTooltip but the addon no longer shows appearances. I'm on the latest update v36.

![image](https://user-images.githubusercontent.com/38279393/202925917-01445073-292a-4514-a4d1-962578f947e2.png)

**Comment by kemayo** [comment]
Hm, yeah, looks like it's only working right now if you have the "zoom in" options enabled. (Which is fortunately the default.)

**Comment by kemayo** [comment]
Ah, and there's an error specifically affecting Forsaken that's stopping the camera from zooming in.

**Comment by kemayo** [comment]
Okay, something about 10.0.0 (or .2, not sure) changed slightly how DressUpModel widgets behave. They now sometimes need a momentary delay after setting them up before you can use their TryOn method -- presumably something about how I'm applying a specific camera view to the zoomed variant avoids this being an issue there.
