### ISSUE TITLE
Anchor Problems

### ISSUE THREAD

**Issue by dle0105** [kemayo/wow-appearancetooltip#13]
I moved my default HuD Tooltip to a location that I prefer and noticed that the appearance window that gets added to the tooltip is always on the top or bottom, regardless of the "Attach to" option selected. This causes the window to overlap with my tooltip. In some (not all) areas of the screen it will work fine. I didn't seem to have this issue before Blizzard updated the UI. 

I've tested it with all other addons disabled as well, no change.

I basically want the window to be on the left side of my tooltip so that it isn't overlapping anything. 

![Untitled-1](https://user-images.githubusercontent.com/12122443/204424929-569990c7-70a5-4941-869e-c382dc5e4ee6.png)

**Comment by kemayo** [comment]
@dle0105 did this fix itself somehow?

**Comment by dle0105** [comment]
> @dle0105 did this fix itself somehow?

No, I’m not sure why I closed it. I was slightly tipsy when I made the ticket, though.

**Comment by kemayo** [comment]
Still better if I fix it, but undeniably a niche issue.
