### ISSUE TITLE
Icon not showing in Bag with bagnon

### ISSUE THREAD

**Issue by gaveer** [kemayo/wow-appearancetooltip#18]
Hello , the icon for apperance not learn not showing with bagnon addon

**Comment by gaveer** [comment]
![Screenshot_1](https://github.com/kemayo/wow-appearancetooltip/assets/45834601/aa93e3f7-4f50-4834-b487-39c8f2b1641d)

**Comment by gaveer** [comment]
@kemayo

**Comment by kemayo** [comment]
Sorry for the slow response -- should be fixed as of 2d872295658fe600f4f4549d0bd31da2c4b57c81.
