### ISSUE TITLE
AppearanceTooltip/overlays.lua:459: Usage: hooksecurefunc([table,] "function", hookfunc) [string "=[C]"]: in function `hooksecurefunc'

### ISSUE THREAD

**Issue by Quartzfire** [kemayo/wow-appearancetooltip#20]
Hi,

This LUA pops up when I log in.

Have checked with PlusMouse (baganator developer) and he's commented to me : "That's a AppearanceTooltip issue, as it hooked into a function that has been moved"

LUA
8x AppearanceTooltip/overlays.lua:459: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@AppearanceTooltip/overlays.lua"]:459: in function <AppearanceTooltip/overlays.lua:457>
[string "=[C]"]: in function `Initialize'
[string "@Baganator/Core/Main.lua"]:11: in function `cb'
[string "@Baganator/Core/Utilities.lua"]:12: in function <Baganator/Core/Utilities.lua:9>

Locals:
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML/ActionButton.lua:73
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 776
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 418
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 372
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:821
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 MANA = "Mana"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML/FloatingChatFrame.lua:2391
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML/AutoComplete.lua:368
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @FrameXML/UIParent.lua:1164
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 JoinSkirmish = <function> defined =[C]:-1
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML/ChatFrame.lua:1167
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 ATLAS_DDL_CONTINENT_BROKENISLES2 = "|TInterface\ICONS\Achievements_Zone_BrokenShore:0:0|t Broken Isles Raids"
 MultiBar5Button11Shine4 = MultiBar5Button11Shine4 {
 }
 TutorialFrame_OnMouseDown = <function> defined @FrameXML/TutorialFrame.lua:262
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 StanceButton8Shine15 = StanceButton8Shine15 {
 }
 EMOTE69_CMD1 = "/nosepick"
 WL_DESC_LOCA

**Comment by kemayo** [comment]
7142c3e4f9eb8338150a594bff23519f6ec7c5e2 fixes this, thanks for letting me know!

**Comment by AngryMustache** [comment]
Slightly new conflict with baganator going on that's very similar to this, in the most recent version:

```
7x AppearanceTooltip/overlays.lua:467: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@AppearanceTooltip/overlays.lua"]:467: in function <AppearanceTooltip/overlays.lua:457>
[string "=[C]"]: in function `Initialize'
[string "@Baganator/Core/Main.lua"]:11: in function `cb'
[string "@Baganator/Core/Utilities.lua"]:12: in function <Baganator/Core/Utilities.lua:9>

Locals:
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML/ActionButton.lua:73
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 776
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 418
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 372
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:821
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 MANA = "Mana"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML/FloatingChatFrame.lua:2391
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML/AutoComplete.lua:368
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @FrameXML/UIParent.lua:1164
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 JoinSkirmish = <function> defined =[C]:-1
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML/ChatFrame.lua:1167
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MultiBar5Button11Shine4 = MultiBar5Button11Shine4 {
 }
 TutorialFrame_OnMouseDown = <function> defined @FrameXML/TutorialFrame.lua:262
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 StanceButton8Shine15 = StanceButton8Shine15 {
 }
 EMOTE69_CMD1 = "/nosepick"
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 SPELL_FAILED_CUSTOM_ERROR_152 = "You must choose a specializati
```

Line 467 appears to be `hooksecurefunc(Baganator_BankOnlyViewFrame.ReagentBankLive, "RebuildLayout", baganator_rebuildlayout)`

If I comment out the line the error goes away, no idea if that hook still exists or not.

**Comment by kemayo** [comment]
I'll actually do the release containing the new API stuff, I suppose. I gave it a bit to turn up issues for people running the alpha.
