### ISSUE TITLE
Error with prepatch. Non-critical 

### ISSUE THREAD

**Issue by xoDragonsbadxo** [kemayo/wow-appearancetooltip#21]
Hello,
I'm just letting you know that there is an error loading the game. It doesn't seem to be critical as much as an annoyance. This happens when no other add-ons are enabled. Thanks so much for this great addon. It made my transmog journey so much better than it would have been :)

24x AppearanceTooltip/config.lua:209: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@AppearanceTooltip/config.lua"]:209: in main chunk

Locals:
myname = "AppearanceTooltip"
ns = <table> {
 SLOT_WAIST = 6
 SLOT_TABARD = 19
 SLOT_OFFHAND = 17
 always_remove = <table> {
 }
 SLOT_MAINHAND = 16
 modifiers = <table> {
 }
 SLOT_FEET = 8
 slot_removals = <table> {
 }
 SLOT_HANDS = 10
 SLOT_SHOULDER = 3
 SLOT_ROBE = -99
 slot_facings = <table> {
 }
 SLOT_SHIRT = 4
 SLOT_CHEST = 5
}
panel = Frame {
 name = "AppearanceTooltip"
}
title = FontString {
}
subText = FontString {
}
dressed = AppearanceTooltipOptionsCheckdressed {
 label = AppearanceTooltipOptionsCheckdressedText {
 }
 Text = AppearanceTooltipOptionsCheckdressedText {
 }
 key = "dressed"
 tooltipRequirement = "Show the model wearing your current outfit, apart from the previewed item"
 tooltipText = "Wear your clothes"
 text = AppearanceTooltipOptionsCheckdressedText {
 }
}
uncover = AppearanceTooltipOptionsCheckuncover {
 label = AppearanceTooltipOptionsCheckuncoverText {
 }
 Text = AppearanceTooltipOptionsCheckuncoverText {
 }
 key = "uncover"
 tooltipRequirement = "Remove clothes that would hide the item you're trying to preview"
 tooltipText = "Uncover previewed item"
 text = AppearanceTooltipOptionsCheckuncoverText {
 }
}
mousescroll = AppearanceTooltipOptionsCheckmousescroll {
 label = AppearanceTooltipOptionsCheckmousescrollText {
 }
 Text = AppearanceTooltipOptionsCheckmousescrollText {
 }
 key = "mousescroll"
 tooltipRequirement = "Use the mousewheel to rotate the model in the tooltip"
 tooltipText = "Rotate with mousewheel"
 text = AppearanceTooltipOptionsCheckmousescrollText {
 }
}
spin = AppearanceTooltipOptionsCheckspin {
 label = AppearanceTooltipOptionsCheckspinText {
 }
 Text = AppearanceTooltipOptionsCheckspinText {
 }
 key = "spin"
 tooltipRequirement = "Constantly spin the model while it's displayed"
 tooltipText = "Spin model"
 text = AppearanceTooltipOptionsCheckspinText {
 }
}
notifyKnown = AppearanceTooltipOptionsChecknotifyKnown {
 label = AppearanceTooltipOptionsChecknotifyKnownText {
 }
 Text = AppearanceTooltipOptionsChecknotifyKnownText {
 }
 key = "notifyKnown"
 tooltipRequirement = "Display a label showing whether you know the item appearance already"
 tooltipText = "Display transmog information"
 text = AppearanceTooltipOptionsChecknotifyKnownText {
 }
}
currentClass = AppearanceTooltipOptionsCheckcurrentClass {
 label = AppearanceTooltipOptionsCheckcurrentClassText {
 }
 Text = AppearanceTooltipOptionsCheckcurrentClassText {
 }
 key = "currentClass"
 tooltipRequirement = "Only show previews on items that the current character can collect"
 tooltipText = "Current character only"
 text = AppearanceTooltipOptionsCheckcurrentClassText {
 }
}
byComparison = AppearanceTooltipOptionsCheckbyComparison {
 label = AppearanceTooltipOptionsCheckbyComparisonText {
 }
 Text = AppearanceTooltipOptionsCheckbyComparisonText {
 }
 key = "byComparison"
 tooltipRequirement = "If the comparison tooltip is shown where the preview would want to be, show next to it (this makes it *much* less likely you'll have the preview overlap your cursor)"
 tooltipText = "Show by comparison tooltip"
 text = AppearanceTooltipOptionsCheckbyComparisonText {
 }
}
tokens = AppearanceTooltipOptionsChecktokens {
 label = AppearanceTooltipOptionsChecktokensText {
 }
 Text = AppearanceTooltipOptionsChecktokensText {
 }
 key = "tokens"
 tooltipRequirement = "Show previews for the items which various tokens can be turned in for when mousing over the token"
 tooltipText = "Previews for tokens"
 text = AppearanceTooltipOptionsChecktokensText {
 }
}
zoomWorn = AppearanceTooltipOptionsCheckzoomWorn {
 label = AppearanceTooltipOptionsCheckzoomWornText {
 }
 Text = AppearanceTooltipOptionsCheckzoomWornText {
 }
 key = "zoomWorn"
 tooltipRequirement = "Zoom in on the part of your model which wears the item"
 tooltipText = "Zoom on worn items"
 text = AppearanceTooltipOptionsCheckzoomWornText {
 }
}
zoomHeld = AppearanceTooltipOptionsCheckzoomHeld {
 label = AppearanceTooltipOptionsCheckzoomHeldText {
 }
 Text = AppearanceTooltipOptionsCheckzoomHeldText {
 }
 key = "zoomHeld"
 tooltipRequirement = "Zoom in on the held item being preview

**Comment by kemayo** [comment]
I was going to say that I'd already fixed that and you just needed to update... but apparently I only fixed it for myself locally and forgot to do a release. So, oops. 😅

**Comment by kemayo** [comment]
Okay, fixed with 5730a1b2998dd768b5b96629fcf7c7a5d093b1a9.
