### ISSUE TITLE
Character model faulty

### ISSUE THREAD

**Issue by AmenitradieDruidin** [kemayo/wow-appearancetooltip#3]
Hello, I found the addon today and am thrilled.
But unfortunately it has not been updated since March 12, 2019. Does the addon give up?

Because unfortunately I have 2-3 errors. What is a shame is that you can not change the models. See image. The model's skin does not change. Will there be an update? Or can I unfortunately uninstall the change again? :(

![WoWScrnShot_061720_191624](https://user-images.githubusercontent.com/39033070/84930044-01054f00-b0d1-11ea-8579-521173c04dbf.jpg)

**Comment by kemayo** [comment]
Hmm... actually, not quite fixed. Skin is better, but the trying-on is inconsistent.

**Comment by kemayo** [comment]
I've gone ahead and filed https://github.com/Stanzilla/WoWUIBugs/issues/42 about this. For now I'm just going to disable custom models, since they seem to be broken by WoW.
