### ISSUE TITLE
Appearancetooltip causing error in wow 9.0.1

### ISSUE THREAD

**Issue by martinboy1974** [kemayo/wow-appearancetooltip#4]
The addon gives the quest items in questlog a dark shade and gives this lua error.

Message: Interface\AddOns\AppearanceTooltip\overlays.lua:151: Cannot find a library instance of "AceAddon-3.0".
Time: Fri Oct 16 23:56:29 2020
Count: 1
Stack: Interface\AddOns\AppearanceTooltip\overlays.lua:151: Cannot find a library instance of "AceAddon-3.0".
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\AppearanceTooltip\lib\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@Interface\AddOns\AppearanceTooltip\overlays.lua"]:151: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceAddon-3.0"."

**Comment by kemayo** [comment]
...it's weird that it'd do anything to the quest log, so I'm not sure what's happening there. That said, I made the faulty assumption that AceAddon would exist, so I'll fix that.

**Comment by martinboy1974** [comment]
I just downloaded your update. With no addons enabled, the quest item in the quest tracker remains. As soon as I enable your addon and reload, the quest item in the quest tracker dissapeares until I open the questlog.

**Comment by kemayo** [comment]
Huh, interesting. Give me a minute to go find a quest with a usable item to test.

**Comment by martinboy1974** [comment]
If u use ElvUi, you will also notice, that with only Elvui enabled, the quest item in tracker looks normal. With only ElvUI and your UI enabled, the quest item suddenly get a very dark shade.

**Comment by kemayo** [comment]
I cannot reproduce this issue. I have tested with the `Abduction Reduction` quest in Mechagon just now, with only AppearanceTooltip enabled, and the item always appears in the tracker.

**Comment by martinboy1974** [comment]
> I cannot reproduce this issue. I have tested with the `Abduction Reduction` quest in Mechagon just now, with only AppearanceTooltip enabled, and the item always appears in the tracker.

Thats weird. With every addon disabled but yours, the item in the tracker has dissapeared from the tracker until I open and close the questlog. And after another reaload ui, the item has dissapeared again. Dont know whats happening.

I have event tried with the addons folder cleaned for every addon accept yours and it still happens.

**Comment by kemayo** [comment]
Okay, worked it out! Apparently the scanning of the appearances database I do on-load hits some threshold of too much scanning at once, and for some reason that manifests as the quest item data not loading. This also seems to cause the elvui thing, probably because it doesn't expect an itemdata load failure right at whatever point it's skinning those buttons.

Commit incoming to fix it.

**Comment by kemayo** [comment]
Thanks for your help in pointing this one out!

**Comment by martinboy1974** [comment]
Sorry, but I am still getting the darkened quest item in the tracker with your addon version 22 and ElvUI enabled.

https://imgur.com/a/AZUZ3EY

**Comment by kemayo** [comment]
Hmm... could I persuade you to run this command for me: `/run AppearanceTooltipDB.scan_delay = 5` then reload your UI and say whether it helps?

(The default I set was `0.2`, and for me that stopped any issues, but I could see this varying between setups.)

**Comment by martinboy1974** [comment]
ElvUI just released a version 12.01 and now it seems to work, "crossing fingers". Seems some of their code broke some skinning.

**Comment by kemayo** [comment]
Well, let me know if this reoccurs, but if not I guess we can assume it was something ElvUI and I were both contributing to. :D
