### ISSUE TITLE
Not listening to where to appear setting

### ISSUE THREAD

**Issue by Starfighter7201** [kemayo/wow-appearancetooltip#5]
I have appeanrance tooltip set to show the model on the fight or left side of the tooltip, but after showing there for a very short time it immediatly switches to bottom/top again.

**Comment by kemayo** [comment]
I'm not seeing this occur:

![image](https://user-images.githubusercontent.com/2187/96350822-3ae56280-107d-11eb-9f90-cc933092bf98.png)

Does this still happen to you if AppearanceTooltip is the only addon you have enabled?
