### ISSUE TITLE
Preview-window blinks frantically when hovering over World Quests that drop items with appearance

### ISSUE THREAD

**Issue by Beet4** [kemayo/wow-appearancetooltip#7]
Like the title says, preview-window blinks frantically when hovering over World Quests that drop items with appearance. Same behavior with World Quest Tracker enabled and without. Also tried only having AppearanceTooltip enabled and results are the same.

Here is a video of the bug:
https://youtu.be/gE6XDD7TdrI

**Comment by kemayo** [comment]
Interesting. It didn't do that before, so presumably blizzard has changed something about how they render those tooltips. I shall investigate.
